name:                tasty-in-src
version:             0.1.0.0
github:              "githubuser/tasty-in-src"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tast-in-src#readme>

default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - DeriveFunctor
  - DeriveGeneric
  - DuplicateRecordFields
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - OverloadedLabels
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - UndecidableInstances
  - UnicodeSyntax
  - TupleSections
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wno-partial-type-signatures -Wincomplete-patterns -Wincomplete-uni-patterns
  - -Wno-deprecations -Wall -Wcompat -Wincomplete-record-updates
  - -Wincomplete-uni-patterns -Wredundant-constraints 
  - -Werror
  - -fplugin=RecordDotPreprocessor

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- tasty
- tasty-hunit
- tasty-discover
- text
- record-dot-preprocessor
- record-hasfield
- unordered-containers

library:
  source-dirs: src

executables:
  tasty-in-src:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-in-src

tests:
  tasty-in-src-test:
    main:                Main.hs
    source-dirs:         
      - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - tasty-in-src
